=== SD2E/python-datacatalog/datacatalog/linkedstores/jobs/document.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Description and history of an ETL or analysis job",
    "type": "object",
    "properties": {
        "pipeline_uuid": {
            "description": "UUID of the pipeline which spawned this job",
            "$ref": "pipeline_uuid.json"
        },
        "archive_path": {
            "description": "Path to the job's outputs, relative to the product store",
            "type": "string"
        },
        "data": {
            "description": "Initial run-time parameterization of the job",
            "type": "object"
        },
        "actor_id": {
            "$ref": "abaco_actorid.json"
        },
        "session": {
            "description": "Optional short alphanumeric correlation string",
            "type": "string"
        }
    },
    "required": [
        "pipeline_uuid",
        "archive_path",
        "data"
    ],
    "_filename": "pipelinejob",
    "__uuid_type": "job",
    "__uuid_field": "session",
    "__collection": "jobs",
    "__indexes": [],
    "__identifiers": [
        "uuid"
    ],
    "additionalProperties": false
}

=== SD2E/python-datacatalog/tests/data/jobs/files/1-local-create-tacobot.json
{
    "pipeline_uuid": "f0f417f2-ba8b-5ac4-b421-255b69553391",
    "archive_path": "products/v1/beb14196-a09c-5c93-b0af-0234a8d14123/0e704c02-c1ab-5c4d-8fb9-a68399e9396d/7157e2f6-e231-5fc6-9f50-0519e183dd37/3b98ff33-d982-5cdc-9f02-5a70471e9629/solid-snake-20180913T162843Z",
    "data": {"param1": "value1"},
    "session": "solid-snake"
}

=== SD2E/python-datacatalog/tests/data/pipelinejob/tacobot.json
{
    "pipeline_uuid": "1064aaf1-459c-5e42-820d-b822aa4b3990",
    "archive_path": "/sample/tacc-cloud/agavehelpers/upload",
    "data": {
        "param1": "value1",
        "param2": 1,
        "param3": true,
        "param4": [
            1,
            2,
            3
        ],
        "param5": [
            "a",
            "b",
            "c"
        ]
    },
    "session": "solid-snake"
}
