=== SD2E/python-datacatalog/datacatalog/linkedstores/pipeline/document.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Pipeline",
    "description": "A computation or processing Pipeline definition",
    "definitions": {
        "pipeline_type": {
            "description": "Enumerated class of action performed by the pipeline",
            "type": "string",
            "enum": [
                "generic-process",
                "data-transfer",
                "metadata-management",
                "primary-etl",
                "secondary-etl"
            ],
            "default": "primary-etl"
        }
    },
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "components": {
            "description": "Unordered array of pipeline components (required)",
            "type": "array",
            "minItems": 1,
            "items": {
                "anyOf": [
                    {
                        "$ref": "agave_app.json"
                    },
                    {
                        "$ref": "abaco_actor.json"
                    },
                    {
                        "$ref": "web_service.json"
                    },
                    {
                        "$ref": "deployed_container.json"
                    }
                ]
            }
        },
        "processing_levels": {
            "type": "array",
            "description": "Level(s) of data product produced by the pipeline",
            "minItems": 1,
            "items": {
                "$ref": "processing_level.json"
            },
            "default": []
        },
        "type": {
            "items": {
                "$ref": "#/definitions/pipeline_type"
            }
        },
        "accepts": {
            "type": "array",
            "description": "File types accepted by the pipeline",
            "items": {
                "$ref": "filetype_label.json"
            },
            "default": [
                "*"
            ],
            "minItems": 1
        },
        "produces": {
            "type": "array",
            "description": "File types produced by the pipeline",
            "items": {
                "$ref": "filetype_label.json"
            },
            "default": [
                "*"
            ],
            "minItems": 1
        },
        "id": {
            "description": "Unique string identifier for the pipeline.",
            "type": "string"
        },
        "uuid": {
            "$ref": "pipeline_uuid.json"
        },
        "_visible": {
            "type": "boolean",
            "default": true
        }
    },
    "required": [
        "name",
        "components",
        "id",
        "processing_levels"
    ],
    "additionalProperties": false,
    "_filename": "pipeline",
    "__uuid_type": "pipeline",
    "__uuid_fields": [
        "components"
    ],
    "__collection": "pipelines",
    "__indexes": [],
    "__identifiers": [
        "uuid",
        "id"
    ]
}

=== SD2E/python-datacatalog/bootstrap/pipelines/dna-seq-analysis.json
{
    "name": "DNA-Seq Alignment, VCF, and K-mer Pipeline",
    "id": "urrutia-dna_alignment_app-0.1.0",
    "description": "This pipeline takes pre-processed DNA-seq data, aligns to a reference genome, generates VCFs against that reference with deepvariant and GATK, and generates a list of 21-mers for split reads.",
    "components": [
        {
            "id": "urrutia-dna_alignment_app-0.1.0",
            "inputs": {},
            "parameters": {
                "read1": "*R1*.fastq.gz",
                "read2": "*R2*.fastq.gz",
              	"fasta": "/reference/*.fa",
              	"fai": "/reference/*.fai",
              	"gff": "/reference/*.gff",
              	"interval_file": "/reference/*.interval_list",
              	"dict_file": "/reference/*.dict",
                "CONTAINER_IMAGE": "sd2e/dna_alignment_app:0.1.0"
            }
        },
       {
            "image": "sd2e/gatk_vcf_app:0.1.0",
         	"hostname": "dockerhub"
       },
       {
            "image": "sd2e/deepvariant_vcf_app:0.1.0",
         	"hostname": "dockerhub"
       }
    ],
    "processing_levels": [
        "2"
    ],
    "accepts": [
      	"FASTQ",
		"FASTA",
		"GFF3",
        "BAM",
      	"PLAIN"
    ],
    "produces": [
        "BAM",
      	"BAI",
      	"FASTA",
		"VCF",
      	"BEDGRAPH"
    ]
}

=== SD2E/python-datacatalog/bootstrap/pipelines/eho-proteomics-aggregator.json
{
    "name": "Proetomics Aggregator Pipeline",
    "id": "proteomics-grabber-0.1.0u1",
    "description": "This app grabs proteomics data for a sample/experiment/measurment request along with the relevant metadata, and produces a dataset after appending the relevant metadata and normalizing across samples.",
    "components": [
        {
            "id": "proteomics-grabber-0.1.0u1",
            "inputs": {
                "options_json": "*.json"
            },
            "parameter": {
                "CONTAINER_IMAGE": "sd2e/proteomics-grabber-0.1.0"
            }
        }
    ],
    "processing_levels": [
        "2"
    ],
    "accepts": [
        "JSON",
        "CSV"
    ],
    "produces": [
        "CSV",
        "PNG"
    ]
}

=== SD2E/python-datacatalog/bootstrap/pipelines/urrutia-dna-seq-aggregation.json
{
    "name": "DNA-seq Aggregation and IGV Pipeline",
    "id": "urrutia-dna-aggregation-0.1.0",
    "description": "This app takes an experiment ID, queries for DNA-seq outputs, and loads them into an IGV server in a jupyter notebook",
    "components": [
        {
            "id": "urrutia-dna-aggregation-app-0.1.0",
            "inputs": {},
            "parameters": {
                "experiment_id": "experiment.*",
                "CONTAINER_IMAGE": "sd2e/dnaseq-aggregation-app:0.1.0"
            }
        }
    ],
    "processing_levels": [
        "2"
    ],
    "accepts": [
        "BAM",
        "BAI",
        "VCF",
        "FASTA",
        "GFF3"
    ],
    "produces": [
        "IPYNB+JSON"
    ]
}
