=== SD2E/python-datacatalog/datacatalog/views/pipelinejobs_table/document.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "PipelineJobs Table",
    "title": "PipelineJobsTable",
    "type": "object",
    "properties": {
        "uuid": {
            "description": "Job ID",
            "$ref": "pipelinejob_uuid.json"
        },
        "pipeline": {
            "description": "Pipeline Name",
            "type": "string"
        },
        "state": {
            "description": "Job's current state",
            "$ref": "pipelinejob_statename.json"
        },
        "updated": {
            "description": "When job was last updated",
            "format": "date-time",
            "type": "string"
        },
        "history": {
            "description": "Annotated history of job events",
            "items": {
                "$ref": "pipelinejob_event.json"
            },
            "type": "array"
        },
        "archive_path": {
            "description": "Path to job outputs",
            "type": "string"
        },
        "hpc_path": {
            "description": "Archive path localized for HPC usage",
            "type": "string"
        },
        "jupyter_path": {
            "description": "Archive path localized for Jupyter usage",
            "type": "string"
        },
        "parameters": {
            "description": "Launch Parameters",
            "type": "object"
        }
    },
    "required": [
        "uuid",
        "pipeline",
        "state",
        "updated",
        "history",
        "archive_path",
        "hpc_path",
        "jupyter_path",
        "parameters"
    ],
    "_filename": "pipelinejobs_table",
    "__uuid_type": "generic",
    "__uuid_field": null,
    "__uuid_fields": [],
    "__collection": "pipelinejobs_table",
    "__indexes": [],
    "__identifiers": [],
    "additionalProperties": false
}

=== SD2E/python-datacatalog/tests/data/pipelinejobs_table/example.json
{
    "uuid": "107a6c4a-f354-53d6-b97d-2c497b9b352e",
    "pipeline": "Tacobot 9000",
    "state": "CREATED",
    "updated": "2018-12-14T21:58:39.000+0000",
    "history": [
        {
            "date": "2018-12-14T21:58:39.000+0000",
            "data": {
                "param1": "value123",
                "param4": [
                    1,
                    2,
                    3
                ],
                "param5": [
                    "a",
                    "b",
                    "c"
                ],
                "param3": true,
                "param2": 123
            },
            "name": "create",
            "uuid": "1082485f-772b-5215-9591-ecce959f667b"
        }
    ],
    "archive_path": "/products/v2/102d7454f65b57c8b59181e7f62e784b/1039c6df4f485a2e967c5881401eb8c3/10492807b76b5042bb1f5f8e09eca918/1064aaf1459c5e42820db822aa4b3990/unanimous-ungulate-20181214T215839Z",
    "hpc_path": "/work2/projects/SD2E-Community/prod/data/products/v2/102d7454f65b57c8b59181e7f62e784b/1039c6df4f485a2e967c5881401eb8c3/10492807b76b5042bb1f5f8e09eca918/1064aaf1459c5e42820db822aa4b3990/unanimous-ungulate-20181214T215839Z",
    "jupyter_path": "/home/jupyter/sd2e-community/products/v2/102d7454f65b57c8b59181e7f62e784b/1039c6df4f485a2e967c5881401eb8c3/10492807b76b5042bb1f5f8e09eca918/1064aaf1459c5e42820db822aa4b3990/unanimous-ungulate-20181214T215839Z",
    "parameters": {
        "param4": [
            1,
            2,
            3
        ],
        "param1": "value123",
        "param5": [
            "a",
            "b",
            "c"
        ],
        "param3": true,
        "param2": 123
    }
}
