=== SD2E/python-datacatalog/datacatalog/linkedstores/pipelinejob/document.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Description and history of a computing job",
    "title": "PipelineJob",
    "type": "object",
    "definitions": {},
    "properties": {
        "pipeline_uuid": {
            "description": "UUID of the pipeline that created this job",
            "$ref": "pipeline_uuid.json"
        },
        "archive_path": {
            "description": "Absolute path to the job products",
            "type": "string"
        },
        "archive_system": {
            "description": "Agave storage resource housing the job products",
            "type": "string"
        },
        "archive_patterns": {
            "description": "Optional list of regular expressions defining specific outputs in archive_path",
            "type": "array",
            "items": {
                "$ref": "archive_patterns.json"
            }
        },
        "product_patterns": {
            "description": "Optional list of regular expressions defining specific outputs in archive_path",
            "type": "array",
            "items": {
                "$ref": "product_patterns.json"
            }
        },
        "data": {
            "description": "Run-time parameterization of the job",
            "type": "object"
        },
        "agent": {
            "oneOf": [
                {
                    "$ref": "abaco_actorid.json"
                },
                {
                    "$ref": "agave_appid.json"
                }
            ]
        },
        "task": {
            "oneOf": [
                {
                    "$ref": "abaco_execid.json"
                },
                {
                    "$ref": "agave_job_uuid.json"
                }
            ]
        },
        "session": {
            "description": "Short alphanumeric correlation string (optional)",
            "type": "string"
        },
        "updated": {
            "format": "date-time",
            "type": "string",
            "description": "When the job record was last updated"
        },
        "_visible": {
            "type": "boolean",
            "default": true
        },
        "history": {
            "description": "Annotated history of job events",
            "type": "array",
            "items": {
                "$ref": "pipelinejob_event.json"
            }
        },
        "state": {
            "$ref": "pipelinejob_statename.json"
        },
        "generated_by": {
            "items": {
                "$ref": "pipeline_uuid.json"
            },
            "type": "array",
            "maxItems": 1,
            "minItems": 1
        },
        "child_of": {
            "items": {
                "anyOf": [
                    {
                        "$ref": "measurement_uuid.json"
                    }
                ]
            },
            "type": "array"
        },
        "acted_on": {
            "items": {
                "anyOf": [
                    {
                        "$ref": "file_uuid.json"
                    }
                ]
            },
            "type": "array"
        },
        "acted_using": {
            "items": {
                "anyOf": [
                    {
                        "$ref": "reference_uuid.json"
                    }
                ]
            },
            "type": "array"
        }
    },
    "required": [
        "pipeline_uuid",
        "archive_path",
        "data"
    ],
    "_filename": "pipelinejob",
    "__uuid_type": "pipelinejob",
    "__uuid_field": null,
    "__uuid_fields": [
        "pipeline_uuid",
        "child_of",
        "data"
    ],
    "__collection": "jobs",
    "__pipeline_collection": "pipelines",
    "__indexes": [],
    "__identifiers": [
        "uuid"
    ],
    "additionalProperties": false
}

=== SD2E/python-datacatalog/tests/data/pipelinejob/tacobot-2.json
{
    "pipeline_uuid": "10650844-1baa-55c5-a481-5e945b19c065",
    "archive_path": "/sample/tacc-cloud/agavehelpers/upload",
    "archive_patterns": [],
    "archive_system": "data-sd2e-community",
    "generated_by": [
        "106026ac-d0b3-5b01-8a84-64b010d0b58f"
    ],
    "child_of": [
        "10483e8d-6602-532a-8941-176ce20dd05a"
    ],
    "acted_on": [
        "105291c2-0404-5121-b658-7cd83f032bb8",
        "105f8f21-6dd4-51a0-b51a-8d2338d59bd6"
    ],
    "acted_using": [
        "10926b36-c9cd-5f0c-8b3c-f3d366dc34bf",
        "1092d775-0f7c-5b4d-970f-e739711d5f36"
    ],
    "task": null,
    "agent": null,
    "data": {
        "param1": "value1",
        "param2": 1,
        "param3": true,
        "param4": [
            1,
            2,
            3
        ],
        "param5": [
            "a",
            "b",
            "c",
            "d"
        ]
    },
    "session": "earnest-egret"
}
