=== SD2E/python-datacatalog/datacatalog/formats/transcriptic/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Transcriptic Samples Format Classification Schema",
  "$comment": "Generated by Genson from examples; Curated by @mweston",
  "type": "object",
  "properties": {
    "challenge_problem": {
      "type": "string"
    },
    "experiment_id": {
      "type": "string"
    },
    "experiment_reference": {
      "type": "string"
    },
    "experimental_start": {
      "type": "string"
    },
    "experimental_end": {
        "type": "string"
    },
    "experimental_reader_params": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "fluorescence": {
                  "oneOf": [
                  {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "emission": {
                                "type": "string"
                            },
                            "excitation": {
                                "type": "string"
                            },
                            "gain": {
                                "type": "number"
                            }
                        },
                        "required": ["emission", "excitation", "gain"]
                    }
                  },
                  {
                    "type": "object",
                    "properties": {
                        "emission": {
                            "type": "string"
                        },
                        "excitation": {
                            "type": "string"
                        },
                        "gain": {
                            "type": "number"
                        }
                    },
                    "required": ["emission", "excitation", "gain"]
                  }]
                },
                "luminescence": {
                    "type": "object",
                    "properties": {
                        "integration_time": {
                            "type": "string"
                        }
                    },
                    "required": ["integration_time"]
                }
            }
        }
    },
    "calibration_reader_params": {
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "emission": {
                    "type": "string"
                },
                "excitation": {
                    "type": "string"
                },
                "gain": {
                    "type": "number"
                }
            },
            "required": ["emission", "excitation", "gain"]
        }
    },
    "lab": {
      "type": "string"
    },
    "samples": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "contents": {
            "oneOf": [{
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            {
              "type":"string"
            },
            {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "label": {
                          "type": "string"
                        },
                        "concentration": {
                          "type": "string"
                        },
                        "timepoint": {
                          "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "label"
                    ]
                },
                "minItems": 1
            }]
          },
          "experimental_media": {
            "type": "string"
          },
          "files": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "sha256": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "type"
              ]
            }
          },
          "sample_id": {
            "type": "string"
          },
          "strain": {
            "type": "string"
          },
          "temperature": {
            "type": "string"
          },
          "timepoint": {
            "type": "string"
          },
          "tx_sample_id": {
            "type": "string"
          },
          "inoculation_density": {
            "type": "string"
          }
        },
        "required": [
          "files",
          "sample_id",
          "temperature",
          "tx_sample_id"
        ]
      }
    },
    "tasbe_cytometer_configuration": {
      "type": "object",
      "properties": {
        "channels": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
	          },
	          "emission_filter": {
                "type": "object",
                "properties": {
                  "center": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "string"
                  },
                  "width": {
                    "type": "integer"
                  }
                }
              },
              "excitation_wavelength": {
	            "type": "integer"
              }
	        }
	      }
        }        
      }
    }
  },
  "required": [
    "challenge_problem",
    "experiment_id",
    "experiment_reference",
    "lab",
    "samples"
  ]
}

=== SD2E/python-datacatalog/tests/data/formats/files/tx-r1c9pjzjs2c9k_r1c9wva2tpwj7.json
{
    "challenge_problem": "YG",
    "experiment_id": "r1c9pjzjs2c9k_r1c9wva2tpwj7",
    "experiment_reference": "https://docs.google.com/document/d/14wB9eJL3p3oDBkPR6Tzowh_YGyGJ0XAL2vw5-zNwuw0/edit?usp=sharing",
    "experimental_end": "2018-12-21T16:18:28.482-08:00",
    "experimental_start": "2018-12-19T17:20:48.552-08:00",
    "lab": "TX",
    "samples": [
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/od1.csv",
                    "sha256": "bfd87e12d1ba97e1d6f97fe0e5bb1b7dbeaa19b77a94db0c803466c4413dfa16",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "1",
            "sample_id": "MediaControl",
            "standard_for": [],
            "standard_type": "MEDIA_BLANK",
            "strain": "MediaControl",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1c9wmwm7p7ay/ct1c9pjzjywr8u"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/od1.csv",
                    "sha256": "bfd87e12d1ba97e1d6f97fe0e5bb1b7dbeaa19b77a94db0c803466c4413dfa16",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "2",
            "sample_id": "MediaControl",
            "standard_for": [],
            "standard_type": "MEDIA_BLANK",
            "strain": "MediaControl",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1c9wmwm8d79m/ct1c9pjzjywr8u"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/od1.csv",
                    "sha256": "bfd87e12d1ba97e1d6f97fe0e5bb1b7dbeaa19b77a94db0c803466c4413dfa16",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "3",
            "sample_id": "MediaControl",
            "standard_for": [],
            "standard_type": "MEDIA_BLANK",
            "strain": "MediaControl",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1c9wmwm9kkkq/ct1c9pjzjywr8u"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/SpheroControl2__2.fcs",
                    "sha256": "f22eb7e156554e378f8ab5e8ea3aa584ab977ba1eddf1b6c18ddfccacc872471",
                    "type": "FLOW"
                }
            ],
            "replicate": "2",
            "sample_id": "SpheroControl2",
            "standard_for": [
                "WT-Control",
                "WT-Live-ControlWT-Dead-Control",
                "NOR 00 Control"
            ],
            "standard_type": "BEAD_FLUORESCENCE",
            "strain": "SpheroControl2",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2pjktd646/ct1c9wva3q4334"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/SpheroControl1__1.fcs",
                    "sha256": "8a8619eef712218ad7a0db2ae32151c3fc34564ad7b57d033995e24ac3feb190",
                    "type": "FLOW"
                }
            ],
            "replicate": "1",
            "sample_id": "SpheroControl1",
            "standard_for": [
                "WT-Control",
                "WT-Live-ControlWT-Dead-Control",
                "NOR 00 Control"
            ],
            "standard_type": "BEAD_FLUORESCENCE",
            "strain": "SpheroControl1",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2pjknj2ta/ct1c9wva3q4334"
        },
        {
            "contents": [
                "rs1b6z2vgatkq7"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/calibration_od.csv",
                    "sha256": "e807e330747507fe5fc2a6a541234f25abdd9928ca1255fd2872824b2c645239",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "ludox_cal",
            "standard_for": [
                "WT-Dead-Control",
                "WT-Live-Control",
                "NOR 00 Control"
            ],
            "standard_type": "LUDOX",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2htuuk2t2/ct1ca2h688wjqb"
        },
        {
            "contents": [
                "rs1b6z2vgatkq7"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/calibration_od.csv",
                    "sha256": "e807e330747507fe5fc2a6a541234f25abdd9928ca1255fd2872824b2c645239",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "ludox_cal",
            "standard_for": [
                "WT-Dead-Control",
                "WT-Live-Control",
                "NOR 00 Control"
            ],
            "standard_type": "LUDOX",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2htuuk2sy/ct1ca2h688wjqb"
        },
        {
            "contents": [
                "rs1b6z2vgatkq7"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/calibration_od.csv",
                    "sha256": "e807e330747507fe5fc2a6a541234f25abdd9928ca1255fd2872824b2c645239",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "ludox_cal",
            "standard_for": [
                "WT-Dead-Control",
                "WT-Live-Control",
                "NOR 00 Control"
            ],
            "standard_type": "LUDOX",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2htuuhxpy/ct1ca2h688wjqb"
        },
        {
            "contents": [
                "rs1b6z2vgatkq7"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/calibration_od.csv",
                    "sha256": "e807e330747507fe5fc2a6a541234f25abdd9928ca1255fd2872824b2c645239",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "ludox_cal",
            "standard_for": [
                "WT-Dead-Control",
                "WT-Live-Control",
                "NOR 00 Control"
            ],
            "standard_type": "LUDOX",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2htuugukw/ct1ca2h688wjqb"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/calibration_od.csv",
                    "sha256": "e807e330747507fe5fc2a6a541234f25abdd9928ca1255fd2872824b2c645239",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "water_cal",
            "standard_for": [
                "WT-Dead-Control",
                "WT-Live-Control",
                "NOR 00 Control"
            ],
            "standard_type": "WATER",
            "strain": "water_cal",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1ca2htwuu3t9/ct1ca2h688wjqb"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201812q/yeast-gates/r1c9pjzjs2c9k_r1c9wva2tpwj7/calibration_od.csv",
                    "sha256": "e807e330747507fe5fc2a6a541234f25abdd9928ca1255fd2872824b2c645239",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "water_cal",
            "standard_for": [
                "WT-Dead-Control",
                "WT-Live-Control",
                "NOR 00 Control"
            ],
            "standard_type": "WATER",
            "strain": "water_cal",
