=== SD2E/python-datacatalog/schemas/transcriptic_samples_classifier.json
{
    "$comment": "version: 2.2.0#master; generated: 20190807T022110+00:00; source: git@github.com:SD2E/python-datacatalog.git@a69d370",
    "$id": "https://schema.catalog.sd2e.org/schemas/transcriptic_samples_classifier.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "challenge_problem": {
            "type": "string"
        },
        "experiment_id": {
            "type": "string"
        },
        "experiment_reference": {
            "type": "string"
        },
        "lab": {
            "type": "string"
        },
        "samples": {
            "items": {
                "properties": {
                    "contents": {
                        "oneOf": [
                            {
                                "items": {
                                    "type": "string"
                                },
                                "type": "array"
                            },
                            {
                                "type": "string"
                            }
                        ]
                    },
                    "experimental_media": {
                        "type": "string"
                    },
                    "files": {
                        "items": {
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "sha256": {
                                    "type": "string"
                                },
                                "type": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "name",
                                "type"
                            ],
                            "type": "object"
                        },
                        "type": "array"
                    },
                    "inoculation_density": {
                        "type": "string"
                    },
                    "sample_id": {
                        "type": "string"
                    },
                    "strain": {
                        "type": "string"
                    },
                    "temperature": {
                        "type": "string"
                    },
                    "timepoint": {
                        "type": "string"
                    },
                    "tx_sample_id": {
                        "type": "string"
                    }
                },
                "required": [
                    "files",
                    "sample_id",
                    "temperature",
                    "tx_sample_id"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "challenge_problem",
        "experiment_id",
        "experiment_reference",
        "lab",
        "samples"
    ],
    "title": "Transcriptic Samples Format Classification Schema",
    "type": "object"
}

=== SD2E/python-datacatalog/tests/data/formats/files/tx-samples.json
{
    "challenge_problem": "YG",
    "experiment_id": "exp_id",
    "experiment_reference": "https://docs.google.com/document/d/14wB9eJL3p3oDBkPR6Tzowh_YGyGJ0XAL2vw5-zNwuw0/edit?usp=sharing",
    "lab": "TX",
    "samples": [
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "1",
            "sample_id": "7373",
            "strain": "7373",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sb9pv/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "2",
            "sample_id": "7373",
            "strain": "7373",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sb9px/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "3",
            "sample_id": "7373",
            "strain": "7373",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sccsw/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "7373",
            "strain": "7373",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sdfvx/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "5",
            "sample_id": "7373",
            "strain": "7373",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sdfvz/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "1",
            "sample_id": "7374",
            "strain": "7374",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sfp3z/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "2",
            "sample_id": "7374",
            "strain": "7374",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sfp43/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "3",
            "sample_id": "7374",
            "strain": "7374",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8sgs72/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "4",
            "sample_id": "7374",
            "strain": "7374",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8shva3/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "1",
            "sample_id": "wt-control-1",
            "strain": "W303dip1",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8ruyef/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "3",
            "sample_id": "7376",
            "strain": "7376",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8s3jzn/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "5",
            "sample_id": "7375",
            "strain": "7375",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8s93gv/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
                    "type": "PLATE_READER"
                }
            ],
            "replicate": "2",
            "sample_id": "wt-control-1",
            "strain": "W303dip1",
            "temperature": "30:celsius",
            "timepoint": "16:hour",
            "tx_sample_id": "aq1bsuhh8rw3hh/ct1bsmggegqg89"
        },
        {
            "contents": [
                "rs1b4uj7zbdy6m"
            ],
            "experimental_media": "rs1b4uj7zbdy6m",
            "files": [
                {
                    "name": "s3://sd2e-community/uploads/transcriptic/201808/yeast-gates/r1bsmggea748b_r1bsun4yb67e7/od1.csv",
                    "sha256": "a0b7d4c4f5f60c498545bbcb08edcfcf4510aa6b324c1d28431742713d68ecbb",
